name: pycpt-env
dependencies:
  - python>=3.10,<3.11
  - pyyaml>=6.0,<7.0
  - flatten-dict>=0.4.2,<0.5.0
  - jinja2>=3.1.2,<4.0.0
  - pandas>=1.4.2,<2.0.0
  - numpy>=1.22.4,<2.0.0
  - requests>=2.28.0,<3.0.0
  - tabulate>=0.8.9,<0.9.0
  - typer>=0.4.1,<0.5.0
  - psycopg2>=2.8.6,<3.0.0
  - pytest==7.1.2
  - pydantic==1.9.1
